"""empty message

Revision ID: 682438cd84bb
Revises: f878dedc4a76
Create Date: 2024-11-19 09:47:58.704104

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '682438cd84bb'
down_revision = 'f878dedc4a76'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('events', schema=None) as batch_op:
        batch_op.add_column(sa.Column('cost', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('description', sa.String(), nullable=True))
        batch_op.alter_column('time',
               existing_type=postgresql.TIME(),
               type_=sa.String(),
               existing_nullable=False)
        batch_op.alter_column('date',
               existing_type=sa.DATE(),
               type_=sa.String(),
               existing_nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('events', schema=None) as batch_op:
        batch_op.alter_column('date',
               existing_type=sa.String(),
               type_=sa.DATE(),
               existing_nullable=False)
        batch_op.alter_column('time',
               existing_type=sa.String(),
               type_=postgresql.TIME(),
               existing_nullable=False)
        batch_op.drop_column('description')
        batch_op.drop_column('cost')

    # ### end Alembic commands ###
