"""empty message

Revision ID: dede3d670e0a
Revises: 682438cd84bb
Create Date: 2024-11-19 13:04:18.711288

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'dede3d670e0a'
down_revision = '682438cd84bb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('events', schema=None) as batch_op:
        batch_op.alter_column('capacity',
               existing_type=sa.INTEGER(),
               nullable=True)

    with op.batch_alter_table('tickets', schema=None) as batch_op:
        batch_op.add_column(sa.Column('cost', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('type', sa.String(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tickets', schema=None) as batch_op:
        batch_op.drop_column('type')
        batch_op.drop_column('cost')

    with op.batch_alter_table('events', schema=None) as batch_op:
        batch_op.alter_column('capacity',
               existing_type=sa.INTEGER(),
               nullable=False)

    # ### end Alembic commands ###
